import { chromium } from 'playwright-core';
import { chromePath } from './resolve-chrome.mjs';

const EXEC = chromePath();

const BASE = 'http://localhost:5199';

/**
 * Centre and usable radius of the circulation ring, with the ring scrolled to
 * the middle of the viewport first.
 *
 * `getBoundingClientRect()` returns the axis-aligned bounds of a *rotated*
 * element, so once scrolling turns the ring a 376px square reports as ~526 —
 * deriving the drag radius from it puts the path outside the ring and off the
 * top of the screen, where the pointer clamps and the sweep never completes.
 * `offsetWidth` is the layout size and is unaffected by the transform.
 */
async function ringGeometry(p) {
  await p
    .locator('.growth .scene')
    .evaluate((el) => el.scrollIntoView({ block: 'center', behavior: 'instant' }));
  await p.waitForTimeout(700);
  const g = await p.locator('.growth .ring').evaluate((el) => {
    const r = el.getBoundingClientRect();
    return { cx: r.left + r.width / 2, cy: r.top + r.height / 2, d: el.offsetWidth };
  });
  return { ...g, r: g.d / 2 - 12 };
}

const errors = [];

const browser = await chromium.launch({ executablePath: EXEC });

async function page(url, { width = 1440, height = 900 } = {}) {
  const ctx = await browser.newContext({ viewport: { width, height } });
  const p = await ctx.newPage();
  p.on('console', (m) => {
    // Vercel injects analytics scripts that only exist once deployed; their
    // 404 in local dev/preview is expected and not an app error.
    if (
      m.type() === 'error' &&
      !/_vercel\/(insights|speed-insights)/.test(m.location()?.url ?? '')
    ) {
      errors.push(`[console ${url}] ${m.text()} ${m.location()?.url ?? ''}`);
    }
  });
  p.on('pageerror', (e) => errors.push(`[pageerror ${url}] ${e.message}`));
  await p.goto(BASE + url, { waitUntil: 'networkidle' });
  return { ctx, p };
}

function ok(label, cond, extra = '') {
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${label}${extra ? '  ' + extra : ''}`);
  if (!cond) process.exitCode = 1;
}

// ---- 1. Hero: island renders, blob path is generated by the engine ----
{
  const { ctx, p } = await page('/');
  await p.waitForTimeout(1600);

  const d = await p.locator('.hero [data-anim="mos-fill"]').getAttribute('d');
  ok('Mos silhouette generated', !!d && d.length > 400, `${(d || '').length} chars`);

  // The scene now draws on three svgs (far islets, light shafts, the island).
  // Exactly one is the labelled subject; the rest are aria-hidden decoration.
  ok('island svg present', (await p.locator('svg.isle[role="img"]').count()) === 1);
  ok(
    'decorative island layers hidden',
    (await p.locator('svg.isle[aria-hidden="true"]').count()) === 2,
  );

  const monCount = await p.locator('.hero [data-anim="mon-fill"]').count();
  ok('three Mon on the island', monCount === 3, `got ${monCount}`);

  // The blob must actually be animating, not frozen on one frame.
  const d2 = await p.locator('.hero [data-anim="mos-fill"]').getAttribute('d');
  await p.waitForTimeout(700);
  const d3 = await p.locator('.hero [data-anim="mos-fill"]').getAttribute('d');
  ok('silhouette is animating', d2 !== d3);

  // ---- Poke: the line changes and the happy face fades in ----
  const before = await p.locator('.mos-line').innerText();
  await p.locator('.hero [data-anim="mos-fill"]').click({ force: true });
  await p.waitForTimeout(500);
  const after = await p.locator('.mos-line').innerText();
  ok('poke swaps Mos line', before !== after, JSON.stringify(after.slice(0, 24)));

  const happy = await p
    .locator('.hero [data-face="happy"]')
    .evaluate((el) => Number(getComputedStyle(el).opacity));
  ok('poke shows happy face', happy > 0.5, `opacity ${happy}`);

  // ---- Mana cursor takes over ----
  await p.mouse.move(700, 400);
  await p.waitForTimeout(300);
  const cursorHidden = await p.evaluate(() => getComputedStyle(document.body).cursor);
  ok('native cursor hidden', cursorHidden === 'none', cursorHidden);
  const dot = await p.locator('.mana-layer .dot').count();
  ok('mana cursor rendered', dot === 1);

  await ctx.close();
}

// ---- 2. TaskDrift: shards dodge the pointer ----
{
  const { ctx, p } = await page('/');
  // Scroll the way a visitor arrives: the field on screen with the closing line
  // still below the fold, so the gather hasn't fired yet.
  await p.evaluate(() => {
    const f = document.querySelector('.drift .field');
    window.scrollTo({
      top: f.getBoundingClientRect().top + window.scrollY - 90,
      behavior: 'instant',
    });
  });
  await p.waitForTimeout(600);

  const gathered = await p
    .locator('.drift .hint')
    .evaluate((el) => Number(getComputedStyle(el).opacity));
  ok('shards still catchable on arrival', gathered > 0.5, `hint opacity ${gathered}`);

  const shard = p.locator('.drift .shard').first();
  const offset = () =>
    p.locator('.drift .shard-lean').evaluateAll((els) =>
      Math.max(
        ...els.map((e) => {
          const nums = [...(e.style.transform || '').matchAll(/-?[\d.]+px/g)].map((n) =>
            Math.abs(parseFloat(n[0])),
          );
          return nums.length ? Math.max(...nums) : 0;
        }),
      ),
    );

  const box = await shard.boundingBox();
  ok('shards start at rest', (await offset()) < 1);

  // Walk the pointer onto the shard and hold — the ease needs ~620ms to land.
  await p.mouse.move(box.x - 60, box.y + box.height + 60);
  const tx = box.x + box.width / 2 - 18;
  const ty = box.y + box.height / 2 + 14;
  for (let i = 0; i < 12; i++) {
    await p.mouse.move(
      box.x - 60 + ((tx - (box.x - 60)) * i) / 11,
      box.y + box.height + 60 + ((ty - (box.y + box.height + 60)) * i) / 11,
    );
    await p.waitForTimeout(70);
  }
  await p.waitForTimeout(300);
  const moved = await offset();
  ok('task shard dodges the cursor', moved > 8, `${moved.toFixed(1)}px`);

  // Pointer leaving the field must bring them home.
  await p.mouse.move(box.x + 600, box.y - 400);
  await p.waitForTimeout(1100);
  const home = await offset();
  ok('shards ease home when the cursor leaves', home < 3, `${home.toFixed(1)}px`);

  await ctx.close();
}

// ---- 3. SummonStage: picking a request changes which Mon are summoned ----
{
  const { ctx, p } = await page('/');
  await p.locator('.summon .stage').scrollIntoViewIfNeeded();
  await p.waitForTimeout(600);

  const first = await p.locator('.summon .mon-slot').count();
  await p.locator('.summon .chips button').nth(1).click();
  await p.waitForTimeout(500);
  const second = await p.locator('.summon .mon-slot').count();
  ok('request 1 summons 3 Mon', first === 3, `got ${first}`);
  ok('request 2 summons 2 Mon', second === 2, `got ${second}`);

  // Let the timeline finish and confirm the result card arrived.
  await p.waitForTimeout(6000);
  const resultOpacity = await p
    .locator('.summon .result')
    .evaluate((el) => Number(getComputedStyle(el).opacity));
  ok('result card revealed', resultOpacity > 0.9, `opacity ${resultOpacity}`);

  await ctx.close();
}

// ---- 4. MosSheet: mood switch drives the same body ----
{
  const { ctx, p } = await page('/');
  await p.locator('.sheet .viewer').scrollIntoViewIfNeeded();
  await p.waitForTimeout(400);

  const line0 = await p.locator('.sheet .line').innerText();
  await p.locator('.sheet .switch button').first().click();
  await p.waitForTimeout(500);
  const line1 = await p.locator('.sheet .line').innerText();
  ok('mood switch changes Mos line', line0 !== line1);

  const happy = await p
    .locator('.sheet [data-face="happy"]')
    .evaluate((el) => Number(getComputedStyle(el).opacity));
  ok('greeting mood holds happy face', happy > 0.5, `opacity ${happy}`);

  await ctx.close();
}

// ---- 5. GrowthOrbit: dragging the ring advances cycles and grows Mos ----
{
  const { ctx, p } = await page('/');
  await p.locator('.growth .scene').scrollIntoViewIfNeeded();
  await p.waitForTimeout(400);

  const { cx, cy, r } = await ringGeometry(p);

  const scale0 = await p.locator('.growth .core').evaluate((el) => getComputedStyle(el).transform);

  // Two full turns around the centre.
  await p.mouse.move(cx + r, cy);
  await p.mouse.down();
  for (let turn = 0; turn < 2; turn++) {
    for (let a = 0; a <= 360; a += 12) {
      const rad = (a * Math.PI) / 180;
      await p.mouse.move(cx + Math.cos(rad) * r, cy + Math.sin(rad) * r);
    }
  }
  await p.mouse.up();
  await p.waitForTimeout(900);

  const cycleText = await p.locator('.growth .cycle').innerText();
  ok('turning the ring counts cycles', /[1-9]/.test(cycleText), JSON.stringify(cycleText));

  const scale1 = await p.locator('.growth .core').evaluate((el) => getComputedStyle(el).transform);
  ok('Mos grows with cycles', scale0 !== scale1);

  const globs = await p.locator('.growth .glob').count();
  ok('cycles add inner globs', globs > 2, `${globs} globs`);

  await ctx.close();
}

// ---- 6. Mobile: island survives, layers thinned ----
{
  const ctx = await browser.newContext({
    viewport: { width: 390, height: 844 },
    hasTouch: true,
    isMobile: true,
  });
  const p = await ctx.newPage();
  p.on('pageerror', (e) => errors.push(`[pageerror mobile] ${e.message}`));
  await p.goto(BASE + '/', { waitUntil: 'networkidle' });
  await p.waitForTimeout(1400);

  ok('island kept on mobile', (await p.locator('svg.isle[role="img"]').count()) === 1);

  const d = await p.locator('.hero [data-anim="mos-fill"]').getAttribute('d');
  ok('Mos renders on mobile', !!d && d.length > 200);

  const visibleMotes = await p
    .locator('.hero .mote')
    .evaluateAll((els) => els.filter((e) => getComputedStyle(e).display !== 'none').length);
  ok('motes thinned on mobile', visibleMotes === 4, `${visibleMotes} visible`);

  const innerOrbit = await p
    .locator('.orbit-plane.inner')
    .evaluate((el) => getComputedStyle(el).display);
  ok('inner orbit hidden on mobile', innerOrbit === 'none', innerOrbit);

  const cursor = await p.evaluate(() => getComputedStyle(document.body).cursor);
  ok('no cursor takeover on touch', cursor !== 'none', cursor);

  await ctx.close();
}

// ---- 7. Reduced motion: everything settles to its final frame ----
{
  const ctx = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    reducedMotion: 'reduce',
  });
  const p = await ctx.newPage();
  p.on('pageerror', (e) => errors.push(`[pageerror reduced] ${e.message}`));
  await p.goto(BASE + '/', { waitUntil: 'networkidle' });
  await p.waitForTimeout(1200);

  const d = await p.locator('.hero [data-anim="mos-fill"]').getAttribute('d');
  ok('reduced motion still draws Mos', !!d && d.length > 200);

  const cursor = await p.evaluate(() => getComputedStyle(document.body).cursor);
  ok('reduced motion keeps native cursor', cursor !== 'none', cursor);

  await p.locator('.drift').scrollIntoViewIfNeeded();
  await p.waitForTimeout(300);
  const gainOpacity = await p
    .locator('.drift .gain')
    .evaluate((el) => Number(getComputedStyle(el).opacity));
  ok('reduced motion reveals copy', gainOpacity > 0.9, `opacity ${gainOpacity}`);

  await ctx.close();
}

// ---- 8. Japanese locale hydrates ----
{
  const { ctx, p } = await page('/ja');
  await p.waitForTimeout(1000);
  const h1 = await p.locator('h1').innerText();
  ok('ja hero copy', h1.includes('わたしのAI'), JSON.stringify(h1));
  const hint = await p.locator('.drift .hint').innerText();
  ok('ja section copy', /つかんで/.test(hint), JSON.stringify(hint));
  await ctx.close();
}

await browser.close();

console.log('\n--- console/page errors ---');
if (errors.length === 0) console.log('none');
else {
  for (const e of errors) console.log(e);
  process.exitCode = 1;
}
